name: style-check

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'CITATION.cff'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE.txt'
      - 'README.md'
      - 'images/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '.gitignore'
      - 'CITATION.cff'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE.txt'
      - 'README.md'
      - 'images/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv
        uses: ./.github/actions/setup-uv
      - name: Lint check
        run: make lint
